version: "3"
services:

  postgres:
    container_name: bookwise-postgres
    image: postgres:16.2
    environment:
      POSTGRES_DB: bookwise
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"

  spring-boot-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bookwise-ils-application
    ports:
      - 8080:8080
    depends_on:
      - postgres
    environment:
      - 'SERVER_PORT=8080'
      - 'SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/bookwise'
      - 'SPRING_DATASOURCE_USERNAME=admin'
      - 'SPRING_DATASOURCE_PASSWORD=admin'
